<?php
function my_add_meta_tag( $name, $value, $tag )
{
    $element = array(
        '#tag' => 'meta',
        '#attributes' => array(
            'name'=> $name,
            'content' => $value
        )
    );
    drupal_add_html_head($element,$tag);
}
function events_preprocess_page(&$vars)
{
    my_add_meta_tag('description','Events editor','Event editor');
    drupal_add_js(drupal_get_path('module', 'events').'/js/tiny.editor.js','file');
    drupal_add_js(drupal_get_path('module', 'events').'/js/jquery-ui.js','file');
    drupal_add_css(drupal_get_path('module','events').'/css/events.css','file');
    drupal_add_css(drupal_get_path('module','events').'/css/tinyeditor.css','file');
    drupal_add_css(drupal_get_path('module','events').'/css/jquery-ui.css','file');
}
function events_block_info() {
  $blocks['events'] = array(
    'info' => t('Edit events'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function events_help($path, $arg) {
    switch ($path)
    {
        case "admin/help#events":
            return '<p>' .
                t("Edit events in the life of an author/production of a work.")
                . '</p>';
            break;
    }
}
function events_block_view($delta = '') {
  switch ($delta) {
    case 'events':
      $mod_path = drupal_get_path('module', 'events');
      $block['subject'] = t('Edit events');
      $block['content'] = '<script type="text/javascript" src="'.$mod_path
        .'/events.js?target=content&'
        .'docid='.$_GET['docid']
        .'&modpath='.$mod_path.'"></script>';
      return $block;
  }
}
